### ISSUE TITLE
Side bar has focus instead of main section

### ISSUE THREAD

**Issue by LordRust** [fongandrew/hydeout#66]
When loading pages in hydeout the sidebar has the focus instead of the main section. Something that disables the ability to just press page down/page up to scroll the documents. I guess the sensible default should be (as in Hyde) to scroll the posts?

**Comment by fongandrew** [comment]
You're right. That would be the sensible default. The root cause is that both the side and the main section are separate content areas with their own overflow. Unfortunately, I haven't had the time to really keep this theme up to date but if anyone wants to take this on, the fix would probably be to absolutely position the sidebar and nudge the main content area with some padding or margin as appropriate.

**Comment by thedroidgeek** [comment]
For anyone still interested, I've fixed the issue here: https://github.com/thedroidgeek/0x41.cf/commit/f4794c4fb4e5241046d98ce81c6fc4146cd17cb8
But since I don't do webdev, not sure if the code is clean enough for a PR.
