### ISSUE TITLE
Show excerpt settings

### ISSUE THREAD

**Issue by theBrandonWu** [fongandrew/hydeout#67]
I couldn't figure out how to only show excerpts in the index page. Do I need to manually create excerpts on each post, or would it be possible for the theme to automatically use the first paragraph as excerpts?

**Comment by jtutmaher** [comment]
@theBrandonWu not sure if this is still helpful given the timing. The 2 ways i've found in the documentation are to either leverage the excerpt_separator (https://github.com/fongandrew/hydeout/blob/master/_posts/2012-02-03-layout-excerpt-generated.md) or define the excerpt explicitly (https://github.com/fongandrew/hydeout/blob/master/_posts/2012-02-04-layout-excerpt-defined.md). It will help to view these files in 'raw' format. In the former case, you could define the separator as  similar to the documentation and then insert it after the first paragraph of you post in the .md file. This should allow the frontend to parse the excerpt rather than the content and display it in pagination on the homepage.

**Comment by fongandrew** [comment]
Sorry for the long response time but @jtutmaher has it right.
